version: '3.7'

services:
    wevebeeneverywhere:
      build: ./blog
      command: python manage.py runserver 0.0.0.0:8000
      volumes:
        - ./blog/:/usr/src/blog/
      ports:
        - 8000:8000
      env_file:
        - ./.env.dev