# Generated by Django 3.0.7 on 2020-11-28 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('1', 'picture'), ('2', 'video')], default=1, max_length=10)),
                ('title', models.CharField(max_length=250)),
                ('source_url', models.CharField(max_length=400)),
                ('content', models.TextField(default='<p>This content must be written in HTML. See the live preview, code shortcuts above, or google for information on syntax.</p>')),
            ],
        ),
    ]
