# Generated by Django 3.2.8 on 2021-11-02 20:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0003_auto_20211027_1538'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('1', 'picture'), ('2', 'video')], default=1, max_length=10)),
                ('caption', models.CharField(max_length=250)),
                ('file_name', models.UUIDField()),
                ('file_extension', models.CharField(choices=[('1', 'png'), ('2', 'jpg'), ('3', 'jpeg')], default=1, max_length=10)),
                ('source_url', models.CharField(max_length=400)),
                ('source_image_file', models.ImageField(upload_to='post_uploads')),
            ],
        ),
        migrations.RenameModel(
            old_name='blog_post',
            new_name='BlogPost',
        ),
        migrations.RenameModel(
            old_name='post_interactions',
            new_name='PostInteraction',
        ),
    ]
