# Generated by Django 3.2.8 on 2021-11-27 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20211102_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaitem',
            name='post_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='blog.blogpost'),
            preserve_default=False,
        ),
    ]
