# Generated by Django 3.2.9 on 2021-11-30 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_remove_blogpost_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
